image: mcr.microsoft.com/dotnet/sdk:8.0

stages:
  - restore
  - build
  - test

variables:
  DOTNET_CLI_TELEMETRY_OPTOUT: "1"
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: "1"
  NUGET_PACKAGES: "$CI_PROJECT_DIR/.nuget/packages"

restore:
  stage: restore
  script:
    - dotnet restore LootkeyAPI.sln

build:
  stage: build
  script:
    - dotnet build LootkeyAPI.sln --configuration Release

test:
  stage: test
  script:
    - dotnet test LootkeyAPI.sln --configuration Release